Preprocesamiento de datos

El conjunto de datos presentados a continuación contiene información de consumo relativa a los clientes de una empresa de telecomunicaciones. Se presenta:
*   Client_ID: identificador único del cliente.
*   Renta: renta básica del plan.
*   Uso_SMS: número de SMS enviados en el mes.
*   Deuda_Ant: deuda facturada en el mes anterior.
*   Min_callcenter: minutos de llamadas al centro de atención.
*   Antiguedad: antiguedad del cliente (en meses).
*   Uso_MB: total de MB consumidos en el periodo.
*   Deuda_Act: deuda facturada en el mes.
*   Uso_APP: MB consumidas en el APP de la operadora.
*   Min_Tot_3M: cantidad total de minutos de llamadas de los últimos 3meses.
*   Género: (M) para masculino, (F) para femenino.
*   Edad: edad (años cumplidos) del cliente.
*   NSE: nivel socioecónomico del cliente.
*   Estado civil: (S) soltero, (C) casado, (V) viudo.
*   Departamento: lugar de residencia declarada por el cliente.
*   Churn: (1) cliente fuga, (0) cliente no fuga

In [2]:
#Importamos librerias
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder

import warnings
warnings.filterwarnings('ignore')

In [3]:
dataset_completo_url = "Tablon_clientes.csv"

In [4]:
#condicion para no tener problemas con el ; y con el primer indice 0 
df = pd.read_csv(
    dataset_completo_url,
    sep=';',
    index_col=0
)

In [5]:
#Visualizacion de los primeros 5
df.head()

,GENERO,EDAD,NSE,ESTADOCIVIL,DEPARTAMENTO,RENTA,USO_SMS,DEUDA_ANT,MIN_CALLCENTER,ANTIGUEDAD,USO_MB,DEUDA_ACT,USO_APP,CHURN,MIN_TOT_3M
CLIENT_ID,,,,,,,,,,,,,,,
0,F,80,1,S,LIMA,49.047829,49.689196,50.259706,48.384797,70.0,49.034758,48.833764,NaN,0,100
1,M,26,1,C,LIMA,49.884485,49.126422,49.968794,51.132655,73.0,47.901566,48.864555,NaN,1,97
2,F,35,1,NaN,LIMA,49.674159,49.008166,48.994351,47.206821,69.0,50.561100,52.411366,NaN,1,98
3,M,30,1,V,LIMA,50.971497,NaN,50.074096,47.980931,69.0,49.279711,NaN,NaN,0,100
4,F,65,1,NaN,LIMA,52.313414,50.962695,49.619874,46.892785,49.0,51.430192,NaN,NaN,0,99

In [6]:
#descripcion conteo, min y max , percentiles

df.describe()

,EDAD,NSE,RENTA,USO_SMS,DEUDA_ANT,MIN_CALLCENTER,ANTIGUEDAD,USO_MB,DEUDA_ACT,USO_APP,CHURN,MIN_TOT_3M
count,4997.000000,4997.0,4997.000000,4938.000000,4967.000000,4942.000000,4364.000000,4997.000000,4873.000000,2404.000000,4997.000000,4997.000000
mean,40.367020,1.0,49.920460,49.996233,50.002322,49.648676,58.770852,49.664046,52.100426,50.934384,0.668001,99.329398
std,15.021341,0.0,4.162126,0.999000,1.003869,1.931749,9.666747,1.670653,147.138083,1.941698,0.470978,2.386067
min,5.000000,1.0,-140.000000,46.154745,46.433099,42.182816,30.000000,43.882448,46.710618,44.721870,0.000000,88.000000
25%,28.000000,1.0,48.787983,49.319983,49.336476,48.324646,50.000000,48.473757,49.298500,49.741090,0.000000,98.000000
50%,40.000000,1.0,49.948368,49.979600,50.015584,49.599311,53.000000,49.649429,50.008242,50.737098,1.000000,100.000000
75%,53.000000,1.0,51.147116,50.671762,50.688129,50.954613,69.000000,50.876590,50.670771,52.207674,1.000000,101.000000
max,130.000000,1.0,55.868670,53.895572,53.146460,56.371546,73.000000,55.867741,10321.000000,60.880871,1.000000,108.000000

In [11]:
#informacion de tipo de dato en las 15 columnas y ver errores
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4997 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GENERO          4947 non-null   object
 1   EDAD            4997 non-null   int64
 2   NSE             4997 non-null   int64
 3   ESTADOCIVIL     178 non-null    object
 4   DEPARTAMENTO    4997 non-null   object
 5   RENTA           4997 non-null   float64
 6   USO_SMS         4938 non-null   float64
 7   DEUDA_ANT       4967 non-null   float64
 8   MIN_CALLCENTER  4942 non-null   float64
 9   ANTIGUEDAD      4364 non-null   float64
 10  USO_MB          4997 non-null   float64
 11  DEUDA_ACT       4873 non-null   float64
 12  USO_APP         2404 non-null   float64
 13  CHURN           4997 non-null   int64
 14  MIN_TOT_3M      4997 non-null   int64
dtypes: float64(8), int64(4), object(3)
memory usage: 624.6+ KB

In [8]:
#conteo de filas y columnas
df.shape

(4997, 15)

In [9]:
#contar valores nulos por columnas
df.isnull().sum()

GENERO              50
EDAD                 0
NSE                  0
ESTADOCIVIL       4819
DEPARTAMENTO         0
RENTA                0
USO_SMS             59
DEUDA_ANT           30
MIN_CALLCENTER      55
ANTIGUEDAD         633
USO_MB               0
DEUDA_ACT          124
USO_APP           2593
CHURN                0
MIN_TOT_3M           0
dtype: int64

In [15]:
#Valores unicos en cada columna
df.nunique()

GENERO               2
EDAD                55
NSE                  1
ESTADOCIVIL          3
DEPARTAMENTO        15
RENTA             4996
USO_SMS           4938
DEUDA_ANT         4967
MIN_CALLCENTER    4942
ANTIGUEDAD          21
USO_MB            4997
DEUDA_ACT         4873
USO_APP           2404
CHURN                2
MIN_TOT_3M          21
dtype: int64

In [12]:
#muestra los valores q son distintos en la columna EDAD
df["EDAD"].unique()

array([ 80,  26,  35,  30,  65,  31,  61,  22,  56,  64,  25,  44,  52,
        58,  20,  53,  36,  24,  16,  15,  40,  34,  45,  55,  50,  60,
        57,  18,  63,  41,  46,  48,  19,  49,  51,  38,  47,  27,  23,
        21,  32,  59,  39,  29,  62,  17,  33,  54,  42,  43,  37,  28,
       130,   5,   6])

In [17]:
#CORRIGUIENDO VALORES ERRONEOS
#corriguiendo la edad , no deneriamos tener mayores de edad que sean menores a 18 años
#comprobamos
print("Edad - valor mínimo y máximo:")
print(df['EDAD'].min(), df['EDAD'].max())

Edad - valor mínimo y máximo:
5 130

In [29]:
#correguimos
df.loc[df['EDAD'] < 18, 'EDAD'] = 18
df[["EDAD"]].head() #comprobamos en la columna edad

           EDAD
CLIENT_ID
0            80
1            26
2            35
3            30
4            65

In [35]:
#comprobamos los rangos de la edad
print("correcion edad - mínimo y máximo:")
print(df['EDAD'].min(), df['EDAD'].max())

correcion edad - mínimo y máximo:
18 130

In [49]:
#visualizamos valores negativos en renta
print("valores negativos:")
print((df['RENTA'] < 0).sum())
df[["RENTA"]].head()

valores negativos:
0

               RENTA
CLIENT_ID
0          49.047829
1          49.884485
2          49.674159
3          50.971497
4          52.313414

In [50]:
#visualizamos correcion de valores negativos en columna renta
(df['RENTA'] < 0).sum()

np.int64(0)

valores negativos:
2

               RENTA
CLIENT_ID
0          49.047829
1          49.884485
2          49.674159
3          50.971497
4          52.313414

In [41]:
#correguimos
mediana_renta = df[df['RENTA'] >= 0]['RENTA'].median()
df.loc[df['RENTA'] < 0, 'RENTA'] = mediana_renta

In [51]:
#visualizamos correcion
(df['RENTA'] < 0).sum()

np.int64(0)

In [6]:
#ponemos parametros a la edad de 18 hasta 80 años 
df.loc[df['EDAD']<18, 'EDAD'] = 18

In [7]:
ids = df.loc[df['EDAD']>80].index
df = df.drop(index=ids)

In [10]:
df["EDAD"].head(20)

CLIENT_ID
0     80
1     26
2     35
3     30
4     65
5     31
6     61
7     22
8     56
9     64
11    22
12    25
13    44
14    52
15    58
16    26
17    20
18    53
19    65
20    36
Name: EDAD, dtype: int64

In [9]:
#comprobamos 
print(df['EDAD'].min(), df['EDAD'].max())

18 80

In [16]:
#df.to_csv('Modificacion_Tablon_clientes.csv')

In [12]:
#Imputar valores perdidos o vacios
df['ESTADOCIVIL'].value_counts(dropna=False)

ESTADOCIVIL
NaN    4815
C       144
S        26
V         8
Name: count, dtype: int64

In [14]:
#Sumamos los datos vacios de cada columna para ver cuantos hay por columna
df.isnull().sum()

GENERO              50
EDAD                 0
NSE                  0
ESTADOCIVIL       4815
DEPARTAMENTO         0
RENTA                0
USO_SMS             59
DEUDA_ANT           30
MIN_CALLCENTER      55
ANTIGUEDAD         633
USO_MB               0
DEUDA_ACT          124
USO_APP           2589
CHURN                0
MIN_TOT_3M           0
dtype: int64

In [15]:
df["USO_APP"].head()

CLIENT_ID
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: USO_APP, dtype: float64

In [17]:
#En estado civil por ejemplo hay gran cantidad de vacios , podemos remplazar los nulos por constantes
df.drop(columns=["ESTADOCIVIL"],inplace=True)

In [22]:
#Se puede remplazar en la columna uso app , los nulos por ceros
df["USO_APP"]=df["USO_APP"].fillna(0)
df["USO_APP"].head()

CLIENT_ID
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: USO_APP, dtype: float64

In [27]:
df["DEUDA_ACT"].isnull().sum()

np.int64(124)

In [28]:
df.head()

,GENERO,EDAD,NSE,DEPARTAMENTO,RENTA,USO_SMS,DEUDA_ANT,MIN_CALLCENTER,ANTIGUEDAD,USO_MB,DEUDA_ACT,USO_APP,CHURN,MIN_TOT_3M
CLIENT_ID,,,,,,,,,,,,,,
0,F,80,1,LIMA,49.047829,49.689196,50.259706,48.384797,70.0,49.034758,48.833764,0.0,0,100
1,M,26,1,LIMA,49.884485,49.126422,49.968794,51.132655,73.0,47.901566,48.864555,0.0,1,97
2,F,35,1,LIMA,49.674159,49.008166,48.994351,47.206821,69.0,50.561100,52.411366,0.0,1,98
3,M,30,1,LIMA,50.971497,NaN,50.074096,47.980931,69.0,49.279711,NaN,0.0,0,100
4,F,65,1,LIMA,52.313414,50.962695,49.619874,46.892785,49.0,51.430192,NaN,0.0,0,99

In [29]:
#En deuda anterior se tienen pocos null , asi que se puede eliminarlos
df.loc[df.DEUDA_ANT.isnull()].shape

(30, 14)

In [32]:
#eliminamos los 30 null
indices_eliminar = df.loc[df.DEUDA_ANT.isnull()].index
df.drop(indices_eliminar, inplace=True)

In [33]:
#Comprobamos
df.loc[df.DEUDA_ANT.isnull()].shape

(0, 14)

In [34]:
df.isnull().sum()

GENERO             50
EDAD                0
NSE                 0
DEPARTAMENTO        0
RENTA               0
USO_SMS            50
DEUDA_ANT           0
MIN_CALLCENTER     55
ANTIGUEDAD        633
USO_MB              0
DEUDA_ACT         124
USO_APP             0
CHURN               0
MIN_TOT_3M          0
dtype: int64

In [35]:
df.to_csv('Modificacion_Tablon_clientes.csv')